# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0003_auto_20170527_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
