# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0004_node_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='code',
            field=models.CharField(default='', max_length=120),
        ),
    ]
