# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0005_auto_20170527_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='label',
            field=models.CharField(max_length=120),
        ),
    ]
