# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0006_auto_20170527_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
