# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0007_node_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikal',
            name='kategorije',
        ),
        migrations.RemoveField(
            model_name='artikal',
            name='prodavnica',
        ),
        migrations.DeleteModel(
            name='Artikal',
        ),
        migrations.DeleteModel(
            name='Kategorija',
        ),
        migrations.DeleteModel(
            name='Prodavnica',
        ),
    ]
